/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DataMass_spectraInchiHashRouteImport } from './routes/data/mass_spectra/$inchiHash'
import { Route as DataCompoundsInchiHashRouteImport } from './routes/data/compounds/$inchiHash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMass_spectraInchiHashRoute =
  DataMass_spectraInchiHashRouteImport.update({
    id: '/data/mass_spectra/$inchiHash',
    path: '/data/mass_spectra/$inchiHash',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataCompoundsInchiHashRoute = DataCompoundsInchiHashRouteImport.update({
  id: '/data/compounds/$inchiHash',
  path: '/data/compounds/$inchiHash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/': typeof DataIndexRoute
  '/data/compounds/$inchiHash': typeof DataCompoundsInchiHashRoute
  '/data/mass_spectra/$inchiHash': typeof DataMass_spectraInchiHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataIndexRoute
  '/data/compounds/$inchiHash': typeof DataCompoundsInchiHashRoute
  '/data/mass_spectra/$inchiHash': typeof DataMass_spectraInchiHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/': typeof DataIndexRoute
  '/data/compounds/$inchiHash': typeof DataCompoundsInchiHashRoute
  '/data/mass_spectra/$inchiHash': typeof DataMass_spectraInchiHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/'
    | '/data/compounds/$inchiHash'
    | '/data/mass_spectra/$inchiHash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/data/compounds/$inchiHash'
    | '/data/mass_spectra/$inchiHash'
  id:
    | '__root__'
    | '/'
    | '/data/'
    | '/data/compounds/$inchiHash'
    | '/data/mass_spectra/$inchiHash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataIndexRoute: typeof DataIndexRoute
  DataCompoundsInchiHashRoute: typeof DataCompoundsInchiHashRoute
  DataMass_spectraInchiHashRoute: typeof DataMass_spectraInchiHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/mass_spectra/$inchiHash': {
      id: '/data/mass_spectra/$inchiHash'
      path: '/data/mass_spectra/$inchiHash'
      fullPath: '/data/mass_spectra/$inchiHash'
      preLoaderRoute: typeof DataMass_spectraInchiHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/compounds/$inchiHash': {
      id: '/data/compounds/$inchiHash'
      path: '/data/compounds/$inchiHash'
      fullPath: '/data/compounds/$inchiHash'
      preLoaderRoute: typeof DataCompoundsInchiHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataIndexRoute: DataIndexRoute,
  DataCompoundsInchiHashRoute: DataCompoundsInchiHashRoute,
  DataMass_spectraInchiHashRoute: DataMass_spectraInchiHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
